global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "clickhouse-exporter"
    static_configs:
      - targets: ["clickhouse-exporter:9116"]

  - job_name: "minio"
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]
